# Velodyne VLP-16 Point Cloud Conversion Config
velodyne_convert:
  ros__parameters:
    calibration: "/opt/ros/humble/share/velodyne_pointcloud/params/VLP16db.yaml"
    min_range: 0.4
    max_range: 100.0
    view_direction: 0.0
    #view_width: 6.2832
    organize_cloud: false
    target_frame: ""
    fixed_frame: ""
    model: "VLP16"